default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>


development:
  <<: *default
  database: marketplace_dev
  host: localhost
  port: 5432
  username: postgres 
  password: <%= ENV["DB_PASSWORD"] %>

test:
  <<: *default
  database: marketplace_test
  host: localhost
  port: 5432
  username: postgres 
  password: <%= ENV["DB_PASSWORD"] %>

# production:
#   <<: *default
#   database: marketplace_api_production
#   username: marketplace_api
#   password: <%= ENV["MARKETPLACE_API_DATABASE_PASSWORD"] %>